# Deploy InfluxDB

- name: Import InfluxDB GPG signing key
  apt_key: url=https://repos.influxdata.com/influxdb.key state=present

- name: Add InfluxDB repository
  apt_repository: repo='deb https://repos.influxdata.com/ubuntu trusty stable' state=present

- name: Install InfluxDB packages
  apt: name=influxdb state=latest

- name: Modify InfluxDB hostname
  replace:
    dest=/etc/influxdb/influxdb.conf
    regexp='hostname = "localhost"'
    replace='hostname = "{{ ansible_hostname }}"'
    backup=yes

- name: Start the InfluxDB service
  service: name=influxdb state=restarted

- name: Pause while InfluxDB service launches
  pause: seconds=5

- name: Check InfluxDB is up and running
  uri:
    url: http://localhost:8086/ping
    method: GET
    status_code: 204
