---
# defaults file for kapacitor

kapacitor_version: 1.0.0

kapacitor_release_channel: stable

kapacitor_hostname: localhost
kapacitor_data_dir: /var/lib/kapacitor

kapacitor_http_bind_address: ":9092"
kapacitor_http_auth_enabled: false
kapacitor_http_log_enabled: true
kapacitor_http_write_tracing: false
kapacitor_http_pprof_enabled: false
kapacitor_http_https_enabled: false
kapacitor_http_https_certificate: /etc/ssl/kapacitor.pem

kapacitor_logging_file: /var/log/kapacitor/kapacitor.log
kapacitor_logging_level: INFO

kapacitor_replay_dir: /var/lib/kapacitor/replay

kapacitor_storage_boltdb: /var/lib/kapacitor/kapacitor.db

kapacitor_deadman_global: false
kapacitor_deadman_threshold: 0.0
kapacitor_deadman_interval: 10s
kapacitor_deadman_id: "{% raw %}node 'NODE_NAME' in taks '{{ .TaskName }}'{% endraw %}"
kapacitor_deadman_message: "{% raw %}{{ .ID }} is {{ if eq .Level \\\"OK\\\" }}alive{{ else }}dead{{ end }}: {{ index .Fields \\\"collected\\\" | printf \\\"%0.3f\\\" }} points/INTERVAL.{% endraw %}"

kapacitor_influxdb_enabled: false
kapacitor_influxdb_default: true
kapacitor_influxdb_name: localhost
kapacitor_influxdb_urls:
  - http://localhost:8086
kapacitor_influxdb_username: ''
kapacitor_influxdb_password: ''
kapacitor_influxdb_timeout: 0
kapacitor_influxdb_ssl_ca: ''
kapacitor_influxdb_ssl_cert: ''
kapacitor_influxdb_ssl_key: ''
kapacitor_influxdb_insecure_skip_verify: false
kapacitor_influxdb_startup_timeout: 5m
kapacitor_influxdb_disable_subscriptions: false
kapacitor_influxdb_subscription_protocol: http
kapacitor_influxdb_subscriptions_sync_interval: 1m0s
kapacitor_influxdb_udp_bind: ''
kapacitor_influxdb_udp_buffer: 1000
kapacitor_influxdb_udp_read_buffer: 0
kapacitor_influxdb_subscriptions: {}
kapacitor_influxdb_excluded_subscriptions: {}

kapacitor_smtp_enabled: false
kapacitor_smtp_host: localhost
kapacitor_smtp_port: 25
kapacitor_smtp_username: ''
kapacitor_smtp_password: ''
kapacitor_smtp_from: ''
kapacitor_smtp_to: []
kapacitor_smtp_no_verify: false
kapacitor_smtp_idle_timeout: 30s
kapacitor_smtp_global: false
kapacitor_smtp_state_changes_only: false

kapacitor_opsgenie_enabled: false
kapacitor_opsgenie_api_key: ''
kapacitor_opsgenie_teams: []
kapacitor_opsgenie_recipients: []
kapacitor_opsgenie_url: https://api.opsgenie.com/v1/json/alert
kapacitor_opsgenie_recovery_url: https://api.opsgenie.com/v1/json/alert/note
kapacitor_opsgenie_global: false

kapacitor_victorops_enabled: false
kapacitor_victorops_api_key: ''
kapacitor_victorops_routing_key: ''
kapacitor_victorops_url: https://alert.victorops.com/integrations/generic/20131114/alert
kapacitor_victorops_global: false

kapacitor_pagerduty_enabled: false
kapacitor_pagerduty_service_key: ''
kapacitor_pagerduty_url: https://events.pagerduty.com/generic/2010-04-15/create_event.json
kapacitor_pagerduty_global: false

kapacitor_slack_enabled: false
kapacitor_slack_url: ''
kapacitor_slack_channel: ''
kapacitor_slack_global: false
kapacitor_slack_state_changes_only: false

kapacitor_telegram_enabled: false
kapacitor_telegram_url: https://api.telegram.org/bot
kapacitor_telegram_token: ''
kapacitor_telegram_chat_id: ''
kapacitor_telegram_parse_mode: Markdown
kapacitor_telegram_disable_web_page_preview: false
kapacitor_telegram_disable_notification: false
kapacitor_telegram_global: false
kapacitor_telegram_state_changes_only: false

kapacitor_hipchat_enabled: false
kapacitor_hipchat_url: https://subdomain.hipchat.com/v2/room
kapacitor_hipchat_room: ''
kapacitor_hipchat_token: ''
kapacitor_hipchat_global: false
kapacitor_hipchat_state_changes_only: false

kapacitor_alerta_enabled: false
kapacitor_alerta_url: ''
kapacitor_alerta_token: ''
kapacitor_alerta_environment: ''
kapacitor_alerta_origin: Kapacitor

kapacitor_sensu_enabled: false
kapacitor_sensu_addr: "sensu-client:3030"
kapacitor_sensu_source: Kapacitor

kapacitor_reporting_enabled: true
kapacitor_reporting_url: https://usage.influxdata.com

kapacitor_stats_enabled: true
kapacitor_stats_interval: 10s
kapacitor_stats_database: _kapacitor
kapacitor_stats_retention_policy: autogen

kapacitor_talk_enabled: false
kapacitor_talk_url: https://jianliao.com/v2/services/webhook/uuid
kapacitor_talk_author_name: Kapacitor

kapacitor_input_collectd_enabled: false
kapacitor_input_collectd_bind_address: ":25826"
kapacitor_input_collectd_database: collectd
kapacitor_input_collectd_retention_policy: ''
kapacitor_input_collectd_batch_size: 1000
kapacitor_input_collectd_batch_pending: 5
kapacitor_input_collectd_batch_timeout: 10s
kapacitor_input_collectd_typesdb: /usr/share/collectd/types.db

kapacitor_input_opentsdb_enabled: false
kapacitor_input_opentsdb_bind_address: ":4242"
kapacitor_input_opentsdb_database: opentsdb
kapacitor_input_opentsdb_retention_policy: ''
kapacitor_input_opentsdb_consistency_level: one
kapacitor_input_opentsdb_tls_enabled: false
kapacitor_input_opentsdb_certificate: /etc/ssl/influxdb.pem
kapacitor_input_opentsdb_batch_size: 1000
kapacitor_input_opentsdb_batch_pending: 5
kapacitor_input_opentsdb_batch_timeout: 1s
