---
# tasks file for chronograf

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - chronograf

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - chronograf

- name: Create Chronograf configuration file
  become: yes
  template:
    src: config.toml.j2
    dest: /opt/chronograf/config.toml
    owner: chronograf
    group: chronograf
    mode: 0664
  notify:
    - restart chronograf
  tags:
    - chronograf

- name: Ensure Chronograf service is started and enabled on boot
  become: yes
  service:
    name: "{{ chronograf_service_name }}"
    state: started
    enabled: yes
  tags:
    - chronograf
